# This workflow installs node dependencies (using the cache if package-lock.json has not been modified) and runs the tests
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependecies
      run: npm install
    - name: Test 
      run: npm run test
    - name: Coverage/Codecov
      run: npm run test:codecov